music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'
urlpatterns = [
    # /music/
    url(r'^$', views.index, name='music'),

    # /music/754
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music/754/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),


    ]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from website import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))

]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=200)
    album_art = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=300)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    albums = Album.objects.all()
    return render(request, 'music/index.html', {'albums': albums})


def detail(request, album_id):
        album = get_object_or_404(Album, pk=album_id)
        return render(request, 'music/details.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        song_selected = album.song_set.get(pk=request.POST['song'])
    except (Song.DoesNotExist, KeyError):
        return render(request, 'music/details.html', {'album': album, 'error_message': 'You did something wrong'})

    else:
        song_selected.is_favorite = True
        song_selected.save()
        return render(request, 'music/details.html', {'album': album})

website/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse('<h2> Main Home Page</h2>')

music/templates/music/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ album }}</title>
</head>
<body>
<img src="{{ album.album_art }}">
<h3>{{ album.album_title }}</h3>
<h4>{{ album.artist }}</h4>

<h2>Songs</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
        <label for="{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://icons.iconarchive.com/icons/aha-soft/multimedia/16/favourites-star-SH-icon.png">
            {% endif %}
        </label><br>
    {% endfor %}

    <input type="submit" value="Favorite">
</form>

</body>
</html>

music/templates/music/index.html
{% for album in albums %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
    	<link rel="stylesheet" type="text/css" href="" />

    </head>

    <body>
    <section class="section chart-grid">
        <div class="section-content">
            <ul>

                <li><strong>{{ album.id }}.</strong><a
                        href="{%  url 'music:detail' album.id %}"><img
                        src="{{ album.album_art }}"
                        width="100" height="100" alt="{{ album.album_title }}"></a>
                    <h3>
                        <a href="{%  url 'music:detail' album.id %}">{{ album.album_title }}</a></h3><h4><a
                            href="#">{{ album.artist }}</a></h4></li>

            </ul>
        </div>
    </section>

{% endfor %}